## libraries

In [1]:
import numpy as np

In [3]:
import pandas as pd

#### arrary contains same data type data

In [14]:
a = [1,-2,3]
a_array = np.array(a)
a_array

array([ 1, -2,  3])

In [15]:
a_array.dtype

dtype('int64')

In [19]:
b = [[1,2,3],[2,3,4]]
b_array = np.array(b)
print(b_array)
b_array.shape

[[1 2 3]
 [2 3 4]]


(2, 3)