## libraries

In [1]:
import numpy as np

In [2]:
import pandas as pd

#### arrary contains same data type data

In [3]:
a = [1,-2,3]
a_array = np.array(a)
a_array

array([ 1, -2,  3])

In [5]:
a_array.dtype

dtype('int64')

In [4]:
b = [[1,2,3],[2,3,4]]
b_array = np.array(b)
print(b_array)
b_array.shape

[[1 2 3]
 [2 3 4]]


(2, 3)

In [6]:
import random
from datetime import datetime, timedelta

# Generate random data
user_ids = [i for i in range(1, 6)]  # 5 user IDs
user_names = ['User' + str(i) for i in range(1, 6)]  # User names
date_of_joining = [(datetime.now() - timedelta(days=random.randint(0, 1000))).strftime('%Y-%m-%d') for _ in range(5)]  # Random dates

# Create the DataFrame
user_df = pd.DataFrame({
    'user_id': user_ids,
    'user_name': user_names,
    'date_of_joining': date_of_joining
})

print(user_df)

   user_id user_name date_of_joining
0        1     User1      2024-10-26
1        2     User2      2022-07-29
2        3     User3      2024-04-07
3        4     User4      2024-06-07
4        5     User5      2023-03-31


In [7]:
user_df.shape

(5, 3)